# Utiliser l'image officielle de Java
FROM openjdk:17-jdk-slim

# Ajouter le fichier JAR de l'API Gateway
COPY target/api-gateway.jar api-gateway.jar

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Commande pour démarrer l'API Gateway
ENTRYPOINT ["java", "-jar", "/api-gateway.jar"]
