# Utiliser l'image officielle de Java légère
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Copier le fichier JAR de l'API Gateway
COPY target/api-gateway-0.0.1-SNAPSHOT.jar api-gateway.jar

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Commande pour démarrer l'API Gateway
ENTRYPOINT ["java", "-jar", "/app/api-gateway.jar"]
