# Image de base : JRE (Java Runtime Environment) basé sur Eclipse Temurin pour Java 17
FROM eclipse-temurin:17-jre-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier JAR de l'application Spring Boot dans l'image
# Le fichier JAR est généré par Maven dans le dossier `target`
COPY target/users-service-0.0.1-SNAPSHOT.jar users-service.jar

# Exposer le port 8080 (par défaut pour les applications Spring Boot)
EXPOSE 8080

# Définir la commande d'entrée pour exécuter le fichier JAR avec Java
ENTRYPOINT [ "java", "-jar", "/app/users-service.jar" ]
