# Utiliser l'image officielle de Java légère
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Copier le fichier JAR du service Produits
COPY target/products-service-0.0.1-SNAPSHOT.jar products-service.jar

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Commande pour démarrer le service
ENTRYPOINT ["java", "-jar", "/app/products-service.jar"]
