# Utiliser l'image officielle de Java
FROM openjdk:17-jdk-slim

# Ajouter le fichier JAR du service Produits
COPY target/products-service.jar products-service.jar

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Commande pour démarrer le service
ENTRYPOINT ["java", "-jar", "/products-service.jar"]
